CREATE database CURSOSBD 
DEFAULT CHARACTER SET UTF8
DEFAULT COLLATE UTF8_GENERAL_CI;

USE CURSOSBD;

CREATE TABLE CURSOS ( 
ID INT NOT NULL AUTO_INCREMENT,
NOME VARCHAR(255) NOT NULL,
DESCRICAO VARCHAR(255) NOT NULL,
CARGAHOR INT,
TOTALAULA INT,
ANOCURSO INT DEFAULT '2018',
PRIMARY KEY (ID))
DEFAULT CHARSET = UTF8;

INSERT INTO `cursosbd`.`cursos` (`NOME`, `DESCRICAO`, `CARGAHOR`, `TOTALAULA`) 
VALUES ('DATA SCIENCE', 'CURSO DE CIENCIA DE DADOS', '4200', '500'),
('BIOINFORMATICA', 'CURSO DE BIOINFORMATICA', '4100', '400'),
('JAVA', 'CURSO DE JAVA', '4200', '100', '2011'),
('MEDICINA', 'CURSO DE MEDICINA', '4200', '100', '2010');


SET SQL_SAFE_UPDATES = 0;

SELECT * FROM CURSOS;

UPDATE CURSOS SET ANOCURSO = '2010';

UPDATE CURSOS SET ANOCURSO = '2015', NOME = 'JAVA8' WHERE ID = 3;





SELECT * FROM CARRO
INNER JOIN PESCARRO ON PESCARRO.ID_PESSOA = CARRO.IDPESSOA








