CREATE DATABASE HENDRIX;

USE HENDRIX;

CREATE TABLE FUNCIONARIOS(
	MATRICULA INT AUTO_INCREMENT,
	CPF BIGINT (11) NOT NULL,
    NOME VARCHAR (200) NOT NULL,
    DEPART_ID SMALLINT,
    ENDERECO VARCHAR (200),
    TELEFONE VARCHAR (200),
    PRIMARY KEY (MATRICULA)
);

CREATE TABLE CLIENTES(
	ID_CLIENTE SMALLINT AUTO_INCREMENT,
    CPF BIGINT (11) NOT NULL,
    NOME VARCHAR (200) NOT NULL,
    CONTACORRENTE VARCHAR (200) NOT NULL,
    CONTAPOUPANCA VARCHAR (200) NOT NULL,
    ENDERECO VARCHAR (200),
    TELEFONE VARCHAR (200),
    VALOREMCONTA BIGINT, 
    PRIMARY KEY (ID_CLIENTE),
    CONSTRAINT FK_FUNC_CLIENTE FOREIGN KEY (MATRICULA) REFERENCES FUNCIONARIOS(MATRICULA)
);