--TRABALHO BANCO DE DADOS

--DEFINA UM PROBLEMA OU SITUAÇÃO NA QUAL SEJA NECESSÁRIA A CRIAÇÃO DE UM BANCO DE DADOS
--(Ex: Pedidos de uma pizzaria )
--OBS: DESCREVA DETALHADAMENTE.
-- ELABORE 10 PERGUNTAS PARA SEREM RESPONDIDAS COM CONSULTAS.


CREATE DATABASE MEETUP;

USE MEETUP;

CREATE TABLE CATEGORIAS(
	ID_CATEG SMALLINT NOT NULL AUTO_INCREMENT,
    TIPO_DE_MEMBRO VARCHAR(50) NOT NULL,
	PRIMARY KEY (ID_CATEG)
);

CREATE TABLE MEMBROS(
    ID_MEMBRO SMALLINT NOT NULL AUTO_INCREMENT,
    NOME VARCHAR(255) NOT NULL,
    EMAIL VARCHAR(255) NOT NULL,
    TELEFONE BIGINT NOT NULL,
    CIDADE VARCHAR(255) NOT NULL,
    FORMACAO VARCHAR(255) NOT NULL,
    INSTITUICAO VARCHAR(255) NOT NULL,
    DATA_ENTRADA DATE NOT NULL,
    ID_CATEG SMALLINT,
    PRIMARY KEY (ID_MEMBRO),
    CONSTRAINT FK_MEMBRO_CATEGORIA FOREIGN KEY (ID_CATEG) REFERENCES CATEGORIAS(ID_CATEG)
);

CREATE TABLE ENCONTROS(
    ID_ENCONTROS SMALLINT NOT NULL AUTO_INCREMENT,
    NOME_MEETUP VARCHAR(255) NOT NULL,
    DATA_MEETUP DATETIME NOT NULL,
    LOCAL_MEETUP VARCHAR(255) NOT NULL,
    ID_MEMBRO SMALLINT,
    PRIMARY KEY (ID_ENCONTROS)
);

CREATE TABLE CONFIRMACOES(
    ID_ENCONTROS SMALLINT,
    CONFIRMADA VARCHAR (1), 
    COMPARECEU VARCHAR (1),
    CONSTRAINT FK_CONFIRM_ENCONTROS FOREIGN KEY (ID_ENCONTROS) REFERENCES ENCONTROS(ID_ENCONTROS)
);

CREATE VIEW ESTATISTICAS AS
SELECT COUNT(COMPARECEU)
FROM ENCONTROS
WHERE CONFIRMADA = SIM;

CREATE TABLE ESTATISTICAS(
	QTD_PRESENCA VARCHAR(255) NOT NULL,
    PRIMARY KEY (ID_AUTOR),
    CONSTRAINT FK_PRODUTO_CATEGORIA FOREIGN KEY (ID_CATEGORIA) REFERENCES CATEGORIA(ID_CATEGORIA)
);


INSERT INTO CATEGORIAS (TIPO_DE_MEMBRO)
VALUES ('ORGANIZADOR'), ('NORMAL'), ('FUNDADOR');

INSERT INTO MEMBROS (TIPO_DE_MEMBRO)
VALUES ('ORGANIZADOR'), ('NORMAL'), ('FUNDADOR');

CREATE TABLE MEMBROS(
    ID_MEMBRO SMALLINT NOT NULL AUTO_INCREMENT,
    NOME VARCHAR(255) NOT NULL,
    EMAIL VARCHAR(255) NOT NULL,
    TELEFONE BIGINT NOT NULL,
    CIDADE VARCHAR(255) NOT NULL,
    FORMACAO VARCHAR(255) NOT NULL,
    INSTITUICAO VARCHAR(255) NOT NULL,
    DATA_ENTRADA DATE NOT NULL,
    ID_CATEG SMALLINT,
    PRIMARY KEY (ID_MEMBRO),
    CONSTRAINT FK_MEMBRO_CATEGORIA FOREIGN KEY (ID_CATEG) REFERENCES CATEGORIAS(ID_CATEG)
);
